spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USER}
    password: ${env.DATABASE_PASSWORD}
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true


server:
  port: ${env.PORT}
  error:
    whitelabel:
      enabled: false


springdoc:
  api-docs:
    path: /api/retail/docs
  swagger-ui:
    path: /api/retail/index.html
    tagsSorter: alpha
    operationsSorter: method
  packages-to-exclude: "com.ahirajustice.retail.entities,"


app:
  config:
    web-client:
      mail-gun:
        base-url: ${env.MAIL_GUN_BASE_URL}
        api-key: ${env.MAIL_GUN_API_KEY}
    email-service:
      from: ${env.FROM_EMAIL_ADDRESS}
      selected: mail-gun
      template-ids:
        client-created: ${env.CLIENT_CREATED_EMAIL_TEMPLATE}
      subjects:
        client-created: Welcome to Retaila
    access-token-expire-minutes: ${env.ACCESS_TOKEN_EXPIRE_MINUTES}
    secret-key: ${env.SECRET_KEY}
    superuser:
      email: ${env.SUPERUSER_EMAIL}
      first-name: ${env.SUPERUSER_FIRST_NAME}
      last-name: ${env.SUPERUSER_LAST_NAME}
      password: ${env.SUPERUSER_PASSWORD}
    user-token:
      length: 6
      keyspace: 0123456789
      validity-in-seconds: 600
    client:
      identifier:
        length: 10
        keyspace: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
      secret:
        length: 24
        keyspace: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    user-device:
      max-count: 3